### ISSUE TITLE
Missing file?

### ISSUE THREAD

**Issue by badblocks** [qris/pytherma#1]
Trying to run your example, but gives error "ModuleNotFoundError: No module named 'pytherma.core'":

```
from pytherma.core import Pytherma

pytherma = Pytherma(serial.Serial('COM3', 9600, timeout=1))
values = pytherma.poll()
print(values)
print(values[144])
print(values[144].value)

```

Where is the "core.py" file or am I lacking knowledge?

**Comment by qris** [comment]
Sorry about that, the example was very speculative and out of date. I've rewritten it to reflect the new reality, and updated the docs significantly.
